-- +goose Up
-- +goose StatementBegin
CREATE TABLE rooms (
  room_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_rooms_created_by
    FOREIGN KEY (created_by) REFERENCES users(id)
    ON DELETE CASCADE
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS rooms;
-- +goose StatementEnd